#!/usr/bin/env bash
HISTSIZE=0
set +o history
#
# This script gets projects from git-able URL's and creates a bjorg managable package.
# Project should have a .bjorg/ directory @root containing build instructions
#
# Built for...
# OS: debian 10

# Make sure args are supplied
if [ $# -eq 0 ]
  then
    echo " -PROJECT_NAME -FQDN -GIT_URL -CONTACT_EMAIL"
    exit 1
fi

# Catch incoming args
PROJECT_NAME=$1
FQDN=$2
GIT_URL=$3
CONTACT_EMAIL=$4

# Set some messy path variables
# This assumes you are where we think you are...
BJORG_CORE=${PWD%/*}
PROJECT_CORE="$BJORG_CORE"/project_core
PROJECT_PATH="$PROJECT_CORE"/"$PROJECT_NAME"
PROJECT_SOURCE_PATH="$PROJECT_PATH"/src

# make project directory in project_core with associated conf
mkdir "$PROJECT_PATH"
mkdir "$PROJECT_SOURCE_PATH"
# probably need more thought on the config handling...
touch "$PROJECT_PATH"/bjorg.ini
cat <<EOT > "$PROJECT_PATH"/bjorg.ini
PROJECT_NAME=$PROJECT_NAME
FQDN=$FQDN
GIT_URL=$GIT_URL
CONTACT_EMAIL=$CONTACT_EMAIL
EOT

# clone project and extract bjorg components
git clone "$GIT_URL" "$PROJECT_SOURCE_PATH"
mv "$PROJECT_SOURCE_PATH"/.bjorg/* "$PROJECT_PATH"
rmdir "$PROJECT_SOURCE_PATH"/.bjorg
