#!/usr/bin/env bash

read -d '' CRON_JOBS << EOF
$1
EOF

# add cron if necessary
if [[ ! -z "$CRON_JOBS" ]]
    then
        echo "INSTALLING CRON JOBS..."
        # Add our jobs to crontab
        (crontab -l ; echo "$CRON_JOBS") | crontab -
fi
